### ISSUE TITLE
help how to use vagrantfile

### ISSUE THREAD

**Issue by diskmanti** [rcompos/zero#1]
Hello, I stumbled upon your repo while looking how to create a local dev env for k8s. You have done a great job regarding this but I have trouble understanding how you created your Vagrantfile. Some sections are commented out but they look like they are needed. 

Also you wrote on the readme file that vagrant-hostmanager is needed to upate the host files but still you never use it on your vagrantfile.

If it is possible to give a more understanding explanation I would be grateful.

Keep up the good work.
Manti

**Comment by rcompos** [comment]
Hi Amanti,

Please see the basic Vagrantfile here for a more straightforward example.
https://github.com/rcompos/zero/blob/master/Vagrantfile.basic

The vagrant plugin vagrant-hostmanager provides management of the local
/etc/hosts on each guest machine.  Not needed if you have a local DNS
service.  No need to mention this in the Vagrantfile, but you must install
with 'vagrant plugin install vagrant-hostmanager'.

###########################
*Example guest /etc/hosts:*

solidfire@yolo-1:~$ cat /etc/hosts
127.0.0.1 localhost localhost.localdomain

# The following lines are desirable for IPv6 capable hosts
::1 localhost6 localhost6.localdomain
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

127.0.1.1 yolo-1 yolo-1
127.0.1.1 ubuntu-bionic ubuntu-bionic

# Ansible inventory hosts BEGIN
192.168.1.84 yolo-1.cluster.local yolo-1
192.168.1.85 yolo-2.cluster.local yolo-2
192.168.1.86 yolo-3.cluster.local yolo-3
# Ansible inventory hosts END
###########################


###########################

*My current Vagrant specs on macOS:*

~/zero|master ⇒ vagrant version
Installed Version: 2.2.6
Latest Version: 2.2.6

You're running an up-to-date version of Vagrant!
~/zero|master ⇒ vagrant plugin list
vagrant-disksize (0.1.3, global)
  - Version Constraint: > 0
vagrant-hostmanager (1.8.9, global)
  - Version Constraint: > 0
vagrant-share (1.1.9, global)
  - Version Constraint: > 0
vagrant-vbguest (0.20.0, global)
  - Version Constraint: > 0
~/zero|master ⇒

# To start yolo-1, yolo-2 & yolo-3
~/zero|master ⇒ for i in {1..3}; do vagrant up yolo-$i; done

# To stop yolo-1, yolo-2 & yolo-3
~/zero|master ⇒ for i in {1..3}; do vagrant halt yolo-$i; done
###########################

Hope this helps.  Feel free to follow up with questions.

Ron Compos

**Comment by rcompos** [comment]
I pushed some changes with various network configs and some descriptions. Also updated readme.   I hope these make it easier to use.

**Comment by diskmanti** [comment]
Thank you for the very quick feedback. What you have done is very cool. Can I alsi suggest adding support for running this behind a corporate proxy through the vagrant-proxyconf plugin. 

```shell
 if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://192.168.0.2:3128/"
    config.proxy.https    = "http://192.168.0.2:3128/"
    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end
```

Just these piece of code should be enough.

Thank you again.
Amanti
